- name: Install Package Apache
  ansible.builtin.apt:
    name: apache2
    state: latest

- name: Copy app package to www
  ansible.builtin.copy:
    src: /tmp/simple-lamp-master/
    dest: "/var/www/{{ site_name }}"
    owner: www-data
    group: www-data
    remote_src: true

- name: Setup app config
  ansible.builtin.template:
    src: templates/config.php.j2
    dest: "/var/www/{{ site_name }}/config.php"

- name: Setup Apache site
  ansible.builtin.template:
    src: templates/apache.conf.j2
    dest: "/etc/apache2/sites-available/{{ site_name }}.conf"

- name: Enable Apache site
  ansible.builtin.command: "a2ensite {{ site_name }}"

- name: Allow HTTP (port 8080) through UFW
  ufw:
    rule: allow
    port: "{{ site_port }}"
#    proto: tcp

- name: Restart Apache service
  systemd:
    name: apache2
    state: started