version: '3.8'
services:
  php:
    image:  my-php-site
    container_name: my-php-site-container
    build: 
      context: .
      target: dev
    ports:
      - "80:80"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - web-app
    volumes:
      - ./simple-lamp/:/var/www/html/
  mysql:
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./simple-lamp/sql:/var/lib/mysql
      - ./simple-lamp/simple_lamp.sql:/docker-entrypoint-initdb.d/simple-lamp.sql
    environment:
      MYSQL_HOSTNAME: "mysql"
      MYSQL_PORT: 3306
      MYSQL_DATABASE: "simple_lamp"
      MYSQL_USER: "username"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    container_name: mysql
    networks:
      - web-app
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
  memcached:
    image: memcached:latest
    container_name: memcached-web-app
    environment:
      CACHE_SERVER: "memcached"
      STORAGE_OPTION: "hd"
      HD_FOLDER: "uploads"
      LATENCY: 0
      ENABLE_CACHE: true
    ports:
        - 11212:11211
    networks:
      - web-app
    command:
      - -vv

networks:
  web-app:
